### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Queue'

### ISSUE THREAD

**Issue by r26zhao** [openedx/xqueue#386]
Hi, I just install devstack (Hawthorn) on my Mac with docker. When I run the xqueue service, I met the following error:
```Traceback (most recent call last):
  File "/edx/app/xqueue/xqueue/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/xqueue/xqueue/queue/management/commands/run_consumer.py", line 3, in <module>
    from queue.consumer import Worker
  File "/edx/app/xqueue/xqueue/queue/consumer.py", line 8, in <module>
    import requests
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 44, in <module>
    from .util.queue import LifoQueue
  File "/edx/app/xqueue/venvs/xqueue/local/lib/python2.7/site-packages/urllib3/util/queue.py", line 10, in <module>
    class LifoQueue(queue.Queue):
AttributeError: 'module' object has no attribute 'Queue'```

Any idea how to solve this issue? Thanks.

**Comment by nedbat** [comment]
We can't provide support in GitHub issues.  See https://open.edx.org/getting-help for details of joining Slack or the mailing lists.
